### ISSUE TITLE
printing Hello world in pdf (Java)

### ISSUE THREAD

**Issue by AryanP45** [Ccode-lang/Cool-ways-to-write-hello-world#14]
![image](https://user-images.githubusercontent.com/95161886/193385628-57b9348d-bcce-465b-bf53-ec4b08e828d0.png)

![image](https://user-images.githubusercontent.com/95161886/193385605-c7fb26e2-b303-4db7-bcba-185210845260.png)

**Comment by AryanP45** [comment]
@Ccode-lang  Please assign me and label Hacktoberfest if this issue is accecpted

**Comment by Ccode-lang** [comment]
Ok good luck!
