### ISSUE TITLE
Hello World in Matrix Java

### ISSUE THREAD

**Issue by AryanP45** [Ccode-lang/Cool-ways-to-write-hello-world#3]
![image](https://user-images.githubusercontent.com/95161886/193314949-55cfa32e-31b0-4e5b-880c-46a970c36ed4.png)

**Comment by Ccode-lang** [comment]
oooh, this looks cool.  nice job :smiley:

**Comment by AryanP45** [comment]
Please edit the CONTRIBUTION.md 
And specify where to add new code file :)

**Comment by AryanP45** [comment]
Contribution Done ! @Ccode-lang  
#12
